# Generated by Django 4.2.7 on 2023-11-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_formatted_address_homepage_latlng_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='latlng_address',
        ),
    ]
