# Generated by Django 4.2.7 on 2023-12-03 17:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_formatted_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_text', wagtail.blocks.RichTextBlock(max_length=255))], blank=True, null=True, use_json_field=True),
        ),
    ]
