# Generated by Django 4.2.7 on 2023-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_logo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='logo_txt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
